version: '2.4'

services:

    kiba1:
        image: wachira90/kibana:7.10.1
        container_name: kibana1
        environment:
            - "ELASTICSEARCH_URL=http://elastic1:9200"
        ports:
            - "5601:5601"
        networks:
            elastic_lan:

    elasticsearch:
        image: wachira90/elastic:7.10.1
        container_name: elasticsearch
        environment:
            - "discovery.type=single-node"
        ports:
            - "9300:9300"
            - "9200:9200"
        networks:
            elastic_lan:

    logstash:
        image: wachira90/logstash:7.10.1
        container_name: logstash
#        volumes:
#            - ./pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
        ports:
            - "5044:5044"
            - "9600:9600"

networks:
    elastic_lan:
